version: 2
updates:
  # github-actions is most important since the only alternative way of finding updates is manually checking the GitHub Actions page
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
  # While I normally find this very annoying and time consuming for a project that is not actively being maintained, since this is open source and representative of my skills, I want to keep it up to date
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
