version: 2
updates:
  # github-actions is most important since the only alternative way of finding updates is manually checking the GitHub Actions page
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
