// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client'

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] }

type ArticleDocumentDataSlicesSlice =
  | ContentSliceSlice
  | HeroSliceSlice
  | AngleSliceSlice

/**
 * Content for Article documents
 */
interface ArticleDocumentData {
  /**
   * Title field in *Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Description (meta) field in *Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField

  /**
   * Pre-title field in *Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article.preTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  preTitle: prismic.KeyTextField

  /**
   * Hero title field in *Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Defaults to the title when empty
   * - **API ID Path**: article.heroTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heroTitle: prismic.KeyTextField

  /**
   * Sub title field in *Article*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article.subTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subTitle: prismic.RichTextField

  /**
   * Slice Zone field in *Article*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: article.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ArticleDocumentDataSlicesSlice>
}

/**
 * Article document from Prismic
 *
 * - **API ID**: `article`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArticleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<ArticleDocumentData>, 'article', Lang>

/**
 * Content for Config documents
 */
interface ConfigDocumentData {
  /**
   * Visit field in *Config*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: config.visit
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  visit: prismic.KeyTextField

  /**
   * Source Code field in *Config*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: config.sourceCode
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sourceCode: prismic.KeyTextField

  /**
   * Language Toggle field in *Config*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Toggle between Dutch and English
   * - **API ID Path**: config.languageToggle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  languageToggle: prismic.KeyTextField

  /**
   * Contact field in *Config*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: config.contact
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  contact: prismic.KeyTextField

  /**
   * Default layout field in *Config*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: config.defaultLayout
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  defaultLayout: prismic.ContentRelationshipField<'layout'>

  /**
   * Articles layout field in *Config*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: config.articlesLayout
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  articlesLayout: prismic.ContentRelationshipField<'layout'>
}

/**
 * Config document from Prismic
 *
 * - **API ID**: `config`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ConfigDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ConfigDocumentData>,
    'config',
    Lang
  >

type LayoutDocumentDataSlicesSlice =
  | PageContentSlice
  | FooterSliceSlice
  | AngleSliceSlice
  | ContentSliceSlice

/**
 * Content for Layout documents
 */
interface LayoutDocumentData {
  /**
   * Slice Zone field in *Layout*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<LayoutDocumentDataSlicesSlice>
}

/**
 * Layout document from Prismic
 *
 * - **API ID**: `layout`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LayoutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<LayoutDocumentData>,
    'layout',
    Lang
  >

type PageDocumentDataSlicesSlice =
  | HeroSliceSlice
  | ContentSliceSlice
  | ProjectsSliceSlice
  | FooterSliceSlice
  | AngleSliceSlice
  | FileDownloadSlice

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Layout field in *Page*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: page.layout
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  layout: prismic.ContentRelationshipField<'layout'>

  /**
   * Head Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.headTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  headTitle: prismic.KeyTextField

  /**
   * Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField

  /**
   * OpenGraph Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.ogImage
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  ogImage: prismic.ImageField<never>

  /**
   * Include in sitemap field in *Page*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: page.sitemap
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  sitemap: prismic.BooleanField

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, 'page', Lang>

/**
 * Content for Project documents
 */
interface ProjectDocumentData {
  /**
   * Thumbnail field in *Project*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.thumbnail
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  thumbnail: prismic.ImageField<never>

  /**
   * Name field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField

  /**
   * Brief field in *Project*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.brief
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  brief: prismic.RichTextField

  /**
   * Started Year field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.startedYear
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  startedYear: prismic.KeyTextField

  /**
   * Ended Year field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Last contribution year
   * - **API ID Path**: project.endedYear
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  endedYear: prismic.KeyTextField

  /**
   * Url field in *Project*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: project.url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url: prismic.LinkField

  /**
   * Source Code field in *Project*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: project.sourceCode
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  sourceCode: prismic.LinkField

  /**
   * Tech field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.tech
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tech: prismic.KeyTextField

  /**
   * Highlighted field in *Project*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: project.highlighted
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  highlighted: prismic.BooleanField

  /**
   * Placeholder field in *Project*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: project.placeholder
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  placeholder: prismic.BooleanField
}

/**
 * Project document from Prismic
 *
 * - **API ID**: `project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ProjectDocumentData>,
    'project',
    Lang
  >

export type AllDocumentTypes =
  | ArticleDocument
  | ConfigDocument
  | LayoutDocument
  | PageDocument
  | ProjectDocument

/**
 * Default variation for AngleSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: AngleSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AngleSliceSliceDefault = prismic.SharedSliceVariation<
  'default',
  Record<string, never>,
  never
>

/**
 * Inverted variation for AngleSlice Slice
 *
 * - **API ID**: `inverted`
 * - **Description**: AngleSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AngleSliceSliceInverted = prismic.SharedSliceVariation<
  'inverted',
  Record<string, never>,
  never
>

/**
 * Slice variation for *AngleSlice*
 */
type AngleSliceSliceVariation = AngleSliceSliceDefault | AngleSliceSliceInverted

/**
 * AngleSlice Shared Slice
 *
 * - **API ID**: `angle_slice`
 * - **Description**: AngleSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AngleSliceSlice = prismic.SharedSlice<
  'angle_slice',
  AngleSliceSliceVariation
>

/**
 * Primary content in *ContentSlice → Primary*
 */
export interface ContentSliceSliceDefaultPrimary {
  /**
   * Content field in *ContentSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_slice.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField
}

/**
 * Default variation for ContentSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: ContentSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentSliceSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ContentSliceSliceDefaultPrimary>,
  never
>

/**
 * Primary content in *ContentSlice → Primary*
 */
export interface ContentSliceSliceImageLeftPrimary {
  /**
   * Image field in *ContentSlice → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content_slice.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * Content field in *ContentSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_slice.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField
}

/**
 * Image Left variation for ContentSlice Slice
 *
 * - **API ID**: `imageLeft`
 * - **Description**: ContentSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentSliceSliceImageLeft = prismic.SharedSliceVariation<
  'imageLeft',
  Simplify<ContentSliceSliceImageLeftPrimary>,
  never
>

/**
 * Primary content in *ContentSlice → Primary*
 */
export interface ContentSliceSliceImageLeftInvertedPrimary {
  /**
   * Image field in *ContentSlice → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content_slice.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * Content field in *ContentSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_slice.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField
}

/**
 * Image Left (inverted) variation for ContentSlice Slice
 *
 * - **API ID**: `imageLeftInverted`
 * - **Description**: ContentSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentSliceSliceImageLeftInverted = prismic.SharedSliceVariation<
  'imageLeftInverted',
  Simplify<ContentSliceSliceImageLeftInvertedPrimary>,
  never
>

/**
 * Primary content in *ContentSlice → Primary*
 */
export interface ContentSliceSliceTwoColumnsTextPrimary {
  /**
   * Content field in *ContentSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_slice.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField
}

/**
 * Two columns text variation for ContentSlice Slice
 *
 * - **API ID**: `twoColumnsText`
 * - **Description**: ContentSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentSliceSliceTwoColumnsText = prismic.SharedSliceVariation<
  'twoColumnsText',
  Simplify<ContentSliceSliceTwoColumnsTextPrimary>,
  never
>

/**
 * Primary content in *ContentSlice → Primary*
 */
export interface ContentSliceSliceTwoColumnsTextInvertedPrimary {
  /**
   * Content field in *ContentSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_slice.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField
}

/**
 * Two columns text (inverted) variation for ContentSlice Slice
 *
 * - **API ID**: `twoColumnsTextInverted`
 * - **Description**: ContentSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentSliceSliceTwoColumnsTextInverted =
  prismic.SharedSliceVariation<
    'twoColumnsTextInverted',
    Simplify<ContentSliceSliceTwoColumnsTextInvertedPrimary>,
    never
  >

/**
 * Primary content in *ContentSlice → Primary*
 */
export interface ContentSliceSliceInvertedPrimary {
  /**
   * Content field in *ContentSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_slice.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField
}

/**
 * Inverted variation for ContentSlice Slice
 *
 * - **API ID**: `inverted`
 * - **Description**: ContentSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentSliceSliceInverted = prismic.SharedSliceVariation<
  'inverted',
  Simplify<ContentSliceSliceInvertedPrimary>,
  never
>

/**
 * Primary content in *ContentSlice → Primary*
 */
export interface ContentSliceSliceArticleMainPrimary {
  /**
   * Content field in *ContentSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_slice.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField
}

/**
 * Article Main variation for ContentSlice Slice
 *
 * - **API ID**: `articleMain`
 * - **Description**: ContentSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentSliceSliceArticleMain = prismic.SharedSliceVariation<
  'articleMain',
  Simplify<ContentSliceSliceArticleMainPrimary>,
  never
>

/**
 * Slice variation for *ContentSlice*
 */
type ContentSliceSliceVariation =
  | ContentSliceSliceDefault
  | ContentSliceSliceImageLeft
  | ContentSliceSliceImageLeftInverted
  | ContentSliceSliceTwoColumnsText
  | ContentSliceSliceTwoColumnsTextInverted
  | ContentSliceSliceInverted
  | ContentSliceSliceArticleMain

/**
 * ContentSlice Shared Slice
 *
 * - **API ID**: `content_slice`
 * - **Description**: ContentSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentSliceSlice = prismic.SharedSlice<
  'content_slice',
  ContentSliceSliceVariation
>

/**
 * Primary content in *FileDownload → Primary*
 */
export interface FileDownloadSliceDefaultPrimary {
  /**
   * File field in *FileDownload → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: file_download.primary.file
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  file: prismic.LinkToMediaField
}

/**
 * Default variation for FileDownload Slice
 *
 * - **API ID**: `default`
 * - **Description**: FileDownload
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FileDownloadSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<FileDownloadSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *FileDownload*
 */
type FileDownloadSliceVariation = FileDownloadSliceDefault

/**
 * FileDownload Shared Slice
 *
 * - **API ID**: `file_download`
 * - **Description**: FileDownload
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FileDownloadSlice = prismic.SharedSlice<
  'file_download',
  FileDownloadSliceVariation
>

/**
 * Primary content in *FooterSlice → Primary*
 */
export interface FooterSliceSliceDefaultPrimary {
  /**
   * Contact Label field in *FooterSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_slice.primary.contactLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  contactLabel: prismic.KeyTextField

  /**
   * Contact Annotation field in *FooterSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_slice.primary.contactAnnotation
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  contactAnnotation: prismic.RichTextField

  /**
   * Email field in *FooterSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_slice.primary.email
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField

  /**
   * Phone field in *FooterSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_slice.primary.phone
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone: prismic.KeyTextField

  /**
   * Whats App field in *FooterSlice → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_slice.primary.whatsApp
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  whatsApp: prismic.NumberField

  /**
   * Social Label field in *FooterSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_slice.primary.socialLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  socialLabel: prismic.KeyTextField

  /**
   * LinkedIn field in *FooterSlice → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_slice.primary.linkedIn
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkedIn: prismic.LinkField

  /**
   * GitHub field in *FooterSlice → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_slice.primary.gitHub
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  gitHub: prismic.LinkField

  /**
   * Twitter field in *FooterSlice → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_slice.primary.twitter
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  twitter: prismic.LinkField

  /**
   * Company Label field in *FooterSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_slice.primary.companyLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  companyLabel: prismic.KeyTextField

  /**
   * Kvk field in *FooterSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_slice.primary.kvk
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  kvk: prismic.KeyTextField

  /**
   * Btw field in *FooterSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_slice.primary.btw
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  btw: prismic.KeyTextField

  /**
   * Iban field in *FooterSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_slice.primary.iban
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  iban: prismic.KeyTextField

  /**
   * Location Label field in *FooterSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_slice.primary.locationLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  locationLabel: prismic.KeyTextField

  /**
   * City field in *FooterSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_slice.primary.city
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  city: prismic.KeyTextField

  /**
   * Location field in *FooterSlice → Primary*
   *
   * - **Field Type**: GeoPoint
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_slice.primary.location
   * - **Documentation**: https://prismic.io/docs/field#geopoint
   */
  location: prismic.GeoPointField
}

/**
 * Default variation for FooterSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: FooterSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterSliceSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<FooterSliceSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *FooterSlice*
 */
type FooterSliceSliceVariation = FooterSliceSliceDefault

/**
 * FooterSlice Shared Slice
 *
 * - **API ID**: `footer_slice`
 * - **Description**: FooterSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterSliceSlice = prismic.SharedSlice<
  'footer_slice',
  FooterSliceSliceVariation
>

/**
 * Primary content in *HeroSlice → Primary*
 */
export interface HeroSliceSliceDefaultPrimary {
  /**
   * Intro field in *HeroSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.primary.intro
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  intro: prismic.RichTextField

  /**
   * Title field in *HeroSlice → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField

  /**
   * Sub Text field in *HeroSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.primary.subText
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subText: prismic.RichTextField

  /**
   * Reactify title field in *HeroSlice → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: hero_slice.primary.reactifyTitle
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  reactifyTitle: prismic.BooleanField
}

/**
 * Default variation for HeroSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: HeroSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<HeroSliceSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *HeroSlice*
 */
type HeroSliceSliceVariation = HeroSliceSliceDefault

/**
 * HeroSlice Shared Slice
 *
 * - **API ID**: `hero_slice`
 * - **Description**: HeroSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceSlice = prismic.SharedSlice<
  'hero_slice',
  HeroSliceSliceVariation
>

/**
 * Default variation for PageContentSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: PageContent
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PageContentSliceDefault = prismic.SharedSliceVariation<
  'default',
  Record<string, never>,
  never
>

/**
 * Slice variation for *PageContentSlice*
 */
type PageContentSliceVariation = PageContentSliceDefault

/**
 * PageContentSlice Shared Slice
 *
 * - **API ID**: `page_content`
 * - **Description**: PageContent
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PageContentSlice = prismic.SharedSlice<
  'page_content',
  PageContentSliceVariation
>

/**
 * Primary content in *ProjectsSlice → Primary*
 */
export interface ProjectsSliceSliceDefaultPrimary {
  /**
   * Title field in *ProjectsSlice → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: This is where it all begins...
   * - **API ID Path**: projects_slice.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField

  /**
   * Explanation field in *ProjectsSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects_slice.primary.explanation
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  explanation: prismic.RichTextField
}

/**
 * Default variation for ProjectsSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: ProjectsSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectsSliceSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ProjectsSliceSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *ProjectsSlice*
 */
type ProjectsSliceSliceVariation = ProjectsSliceSliceDefault

/**
 * ProjectsSlice Shared Slice
 *
 * - **API ID**: `projects_slice`
 * - **Description**: ProjectsSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectsSliceSlice = prismic.SharedSlice<
  'projects_slice',
  ProjectsSliceSliceVariation
>

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>
  }

  namespace Content {
    export type {
      ArticleDocument,
      ArticleDocumentData,
      ArticleDocumentDataSlicesSlice,
      ConfigDocument,
      ConfigDocumentData,
      LayoutDocument,
      LayoutDocumentData,
      LayoutDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      ProjectDocument,
      ProjectDocumentData,
      AllDocumentTypes,
      AngleSliceSlice,
      AngleSliceSliceVariation,
      AngleSliceSliceDefault,
      AngleSliceSliceInverted,
      ContentSliceSlice,
      ContentSliceSliceDefaultPrimary,
      ContentSliceSliceImageLeftPrimary,
      ContentSliceSliceImageLeftInvertedPrimary,
      ContentSliceSliceTwoColumnsTextPrimary,
      ContentSliceSliceTwoColumnsTextInvertedPrimary,
      ContentSliceSliceInvertedPrimary,
      ContentSliceSliceArticleMainPrimary,
      ContentSliceSliceVariation,
      ContentSliceSliceDefault,
      ContentSliceSliceImageLeft,
      ContentSliceSliceImageLeftInverted,
      ContentSliceSliceTwoColumnsText,
      ContentSliceSliceTwoColumnsTextInverted,
      ContentSliceSliceInverted,
      ContentSliceSliceArticleMain,
      FileDownloadSlice,
      FileDownloadSliceDefaultPrimary,
      FileDownloadSliceVariation,
      FileDownloadSliceDefault,
      FooterSliceSlice,
      FooterSliceSliceDefaultPrimary,
      FooterSliceSliceVariation,
      FooterSliceSliceDefault,
      HeroSliceSlice,
      HeroSliceSliceDefaultPrimary,
      HeroSliceSliceVariation,
      HeroSliceSliceDefault,
      PageContentSlice,
      PageContentSliceVariation,
      PageContentSliceDefault,
      ProjectsSliceSlice,
      ProjectsSliceSliceDefaultPrimary,
      ProjectsSliceSliceVariation,
      ProjectsSliceSliceDefault,
    }
  }
}
