// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Article documents */
interface ArticleDocumentData {
    /**
     * Name field in *Article*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: article.name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    name: prismicT.KeyTextField;
    /**
     * Slice Zone field in *Article*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: article.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<ArticleDocumentDataSlicesSlice>;
}
/**
 * Slice for *Article → Slice Zone*
 *
 */
type ArticleDocumentDataSlicesSlice = ArticleCodeSnippetSliceSlice | ArticleContentSliceSlice;
/**
 * Article document from Prismic
 *
 * - **API ID**: `article`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArticleDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<ArticleDocumentData>, "article", Lang>;
/** Content for Config documents */
interface ConfigDocumentData {
    /**
     * Visit field in *Config*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: config.visit
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    visit: prismicT.KeyTextField;
    /**
     * Source Code field in *Config*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: config.sourceCode
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    sourceCode: prismicT.KeyTextField;
    /**
     * Language Toggle field in *Config*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Toggle between Dutch and English
     * - **API ID Path**: config.languageToggle
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    languageToggle: prismicT.KeyTextField;
    /**
     * Contact field in *Config*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: config.contact
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    contact: prismicT.KeyTextField;
}
/**
 * Config document from Prismic
 *
 * - **API ID**: `config`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ConfigDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<ConfigDocumentData>, "config", Lang>;
/** Content for Layout documents */
interface LayoutDocumentData {
    /**
     * Slice Zone field in *Layout*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: layout.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<LayoutDocumentDataSlicesSlice>;
}
/**
 * Slice for *Layout → Slice Zone*
 *
 */
type LayoutDocumentDataSlicesSlice = PageContentSlice | FooterSliceSlice;
/**
 * Layout document from Prismic
 *
 * - **API ID**: `layout`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LayoutDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<LayoutDocumentData>, "layout", Lang>;
/** Content for Page documents */
interface PageDocumentData {
    /**
     * Layout field in *Page*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: page.layout
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    layout: prismicT.RelationField<"layout">;
    /**
     * Head Title field in *Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.headTitle
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    headTitle: prismicT.KeyTextField;
    /**
     * Description field in *Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismicT.KeyTextField;
    /**
     * OpenGraph Image field in *Page*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: page.ogImage
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    ogImage: prismicT.ImageField<never>;
    /**
     * Slice Zone field in *Page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<PageDocumentDataSlicesSlice>;
}
/**
 * Slice for *Page → Slice Zone*
 *
 */
type PageDocumentDataSlicesSlice = HeroSliceSlice | ContentSliceSlice | ProjectsSliceSlice | FooterSliceSlice | AngleSliceSlice | FileDownloadSlice;
/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;
/** Content for Project documents */
interface ProjectDocumentData {
    /**
     * Thumbnail field in *Project*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: project.thumbnail
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    thumbnail: prismicT.ImageField<never>;
    /**
     * Name field in *Project*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: project.name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    name: prismicT.KeyTextField;
    /**
     * Brief field in *Project*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: project.brief
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    brief: prismicT.RichTextField;
    /**
     * Started Year field in *Project*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: project.startedYear
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    startedYear: prismicT.KeyTextField;
    /**
     * Ended Year field in *Project*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Last contribution year
     * - **API ID Path**: project.endedYear
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    endedYear: prismicT.KeyTextField;
    /**
     * Url field in *Project*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: project.url
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    url: prismicT.LinkField;
    /**
     * Source Code field in *Project*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: project.sourceCode
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    sourceCode: prismicT.LinkField;
    /**
     * Tech field in *Project*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: project.tech
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    tech: prismicT.KeyTextField;
    /**
     * Highlighted field in *Project*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: project.highlighted
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
     *
     */
    highlighted: prismicT.BooleanField;
    /**
     * Placeholder field in *Project*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: project.placeholder
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
     *
     */
    placeholder: prismicT.BooleanField;
}
/**
 * Project document from Prismic
 *
 * - **API ID**: `project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<ProjectDocumentData>, "project", Lang>;
export type AllDocumentTypes = ArticleDocument | ConfigDocument | LayoutDocument | PageDocument | ProjectDocument;
/**
 * Default variation for AngleSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: `AngleSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type AngleSliceSliceDefault = prismicT.SharedSliceVariation<"default", Record<string, never>, never>;
/**
 * Inverted variation for AngleSlice Slice
 *
 * - **API ID**: `inverted`
 * - **Description**: `AngleSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type AngleSliceSliceInverted = prismicT.SharedSliceVariation<"inverted", Record<string, never>, never>;
/**
 * Slice variation for *AngleSlice*
 *
 */
type AngleSliceSliceVariation = AngleSliceSliceDefault | AngleSliceSliceInverted;
/**
 * AngleSlice Shared Slice
 *
 * - **API ID**: `angle_slice`
 * - **Description**: `AngleSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type AngleSliceSlice = prismicT.SharedSlice<"angle_slice", AngleSliceSliceVariation>;
/**
 * Primary content in ArticleCodeSnippetSlice → Primary
 *
 */
interface ArticleCodeSnippetSliceSliceDefaultPrimary {
    /**
     * Language field in *ArticleCodeSnippetSlice → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: article_code_snippet_slice.primary.language
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    language: prismicT.KeyTextField;
    /**
     * Content field in *ArticleCodeSnippetSlice → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: article_code_snippet_slice.primary.content
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    content: prismicT.RichTextField;
}
/**
 * Default variation for ArticleCodeSnippetSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: `ArticleCodeSnippetSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ArticleCodeSnippetSliceSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ArticleCodeSnippetSliceSliceDefaultPrimary>, never>;
/**
 * Slice variation for *ArticleCodeSnippetSlice*
 *
 */
type ArticleCodeSnippetSliceSliceVariation = ArticleCodeSnippetSliceSliceDefault;
/**
 * ArticleCodeSnippetSlice Shared Slice
 *
 * - **API ID**: `article_code_snippet_slice`
 * - **Description**: `ArticleCodeSnippetSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ArticleCodeSnippetSliceSlice = prismicT.SharedSlice<"article_code_snippet_slice", ArticleCodeSnippetSliceSliceVariation>;
/**
 * Primary content in ArticleContentSlice → Primary
 *
 */
interface ArticleContentSliceSliceDefaultPrimary {
    /**
     * Content field in *ArticleContentSlice → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: article_content_slice.primary.content
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    content: prismicT.RichTextField;
}
/**
 * Default variation for ArticleContentSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: `ArticleContentSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ArticleContentSliceSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ArticleContentSliceSliceDefaultPrimary>, never>;
/**
 * Slice variation for *ArticleContentSlice*
 *
 */
type ArticleContentSliceSliceVariation = ArticleContentSliceSliceDefault;
/**
 * ArticleContentSlice Shared Slice
 *
 * - **API ID**: `article_content_slice`
 * - **Description**: `ArticleContentSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ArticleContentSliceSlice = prismicT.SharedSlice<"article_content_slice", ArticleContentSliceSliceVariation>;
/**
 * Primary content in ArticleSlice → Primary
 *
 */
interface ArticleSliceSliceDefaultPrimary {
    /**
     * Article field in *ArticleSlice → Primary*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: article_slice.primary.article
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    article: prismicT.RelationField<"article">;
}
/**
 * Default variation for ArticleSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: `ArticleSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ArticleSliceSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ArticleSliceSliceDefaultPrimary>, never>;
/**
 * Slice variation for *ArticleSlice*
 *
 */
type ArticleSliceSliceVariation = ArticleSliceSliceDefault;
/**
 * ArticleSlice Shared Slice
 *
 * - **API ID**: `article_slice`
 * - **Description**: `ArticleSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ArticleSliceSlice = prismicT.SharedSlice<"article_slice", ArticleSliceSliceVariation>;
/**
 * Primary content in ContentSlice → Primary
 *
 */
interface ContentSliceSliceDefaultPrimary {
    /**
     * Content field in *ContentSlice → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: content_slice.primary.content
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    content: prismicT.RichTextField;
}
/**
 * Default variation for ContentSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: `ContentSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ContentSliceSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ContentSliceSliceDefaultPrimary>, never>;
/**
 * Primary content in ContentSlice → Primary
 *
 */
interface ContentSliceSliceImageLeftPrimary {
    /**
     * Image field in *ContentSlice → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: content_slice.primary.image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * Content field in *ContentSlice → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: content_slice.primary.content
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    content: prismicT.RichTextField;
}
/**
 * Image Left variation for ContentSlice Slice
 *
 * - **API ID**: `imageLeft`
 * - **Description**: `ContentSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ContentSliceSliceImageLeft = prismicT.SharedSliceVariation<"imageLeft", Simplify<ContentSliceSliceImageLeftPrimary>, never>;
/**
 * Primary content in ContentSlice → Primary
 *
 */
interface ContentSliceSliceImageLeftInvertedPrimary {
    /**
     * Image field in *ContentSlice → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: content_slice.primary.image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * Content field in *ContentSlice → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: content_slice.primary.content
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    content: prismicT.RichTextField;
}
/**
 * Image Left (inverted) variation for ContentSlice Slice
 *
 * - **API ID**: `imageLeftInverted`
 * - **Description**: `ContentSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ContentSliceSliceImageLeftInverted = prismicT.SharedSliceVariation<"imageLeftInverted", Simplify<ContentSliceSliceImageLeftInvertedPrimary>, never>;
/**
 * Primary content in ContentSlice → Primary
 *
 */
interface ContentSliceSliceTwoColumnsTextPrimary {
    /**
     * Content field in *ContentSlice → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: content_slice.primary.content
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    content: prismicT.RichTextField;
}
/**
 * Two columns text variation for ContentSlice Slice
 *
 * - **API ID**: `twoColumnsText`
 * - **Description**: `ContentSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ContentSliceSliceTwoColumnsText = prismicT.SharedSliceVariation<"twoColumnsText", Simplify<ContentSliceSliceTwoColumnsTextPrimary>, never>;
/**
 * Primary content in ContentSlice → Primary
 *
 */
interface ContentSliceSliceTwoColumnsTextInvertedPrimary {
    /**
     * Content field in *ContentSlice → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: content_slice.primary.content
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    content: prismicT.RichTextField;
}
/**
 * Two columns text (inverted) variation for ContentSlice Slice
 *
 * - **API ID**: `twoColumnsTextInverted`
 * - **Description**: `ContentSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ContentSliceSliceTwoColumnsTextInverted = prismicT.SharedSliceVariation<"twoColumnsTextInverted", Simplify<ContentSliceSliceTwoColumnsTextInvertedPrimary>, never>;
/**
 * Primary content in ContentSlice → Primary
 *
 */
interface ContentSliceSliceInvertedPrimary {
    /**
     * Image field in *ContentSlice → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: content_slice.primary.image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * Content field in *ContentSlice → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: content_slice.primary.content
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    content: prismicT.RichTextField;
}
/**
 * Inverted variation for ContentSlice Slice
 *
 * - **API ID**: `inverted`
 * - **Description**: `ContentSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ContentSliceSliceInverted = prismicT.SharedSliceVariation<"inverted", Simplify<ContentSliceSliceInvertedPrimary>, never>;
/**
 * Slice variation for *ContentSlice*
 *
 */
type ContentSliceSliceVariation = ContentSliceSliceDefault | ContentSliceSliceImageLeft | ContentSliceSliceImageLeftInverted | ContentSliceSliceTwoColumnsText | ContentSliceSliceTwoColumnsTextInverted | ContentSliceSliceInverted;
/**
 * ContentSlice Shared Slice
 *
 * - **API ID**: `content_slice`
 * - **Description**: `ContentSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ContentSliceSlice = prismicT.SharedSlice<"content_slice", ContentSliceSliceVariation>;
/**
 * Primary content in FileDownload → Primary
 *
 */
interface FileDownloadSliceDefaultPrimary {
    /**
     * File field in *FileDownload → Primary*
     *
     * - **Field Type**: Link to Media
     * - **Placeholder**: *None*
     * - **API ID Path**: file_download.primary.file
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    file: prismicT.LinkToMediaField;
}
/**
 * Default variation for FileDownload Slice
 *
 * - **API ID**: `default`
 * - **Description**: `FileDownload`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FileDownloadSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<FileDownloadSliceDefaultPrimary>, never>;
/**
 * Slice variation for *FileDownload*
 *
 */
type FileDownloadSliceVariation = FileDownloadSliceDefault;
/**
 * FileDownload Shared Slice
 *
 * - **API ID**: `file_download`
 * - **Description**: `FileDownload`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FileDownloadSlice = prismicT.SharedSlice<"file_download", FileDownloadSliceVariation>;
/**
 * Primary content in FooterSlice → Primary
 *
 */
interface FooterSliceSliceDefaultPrimary {
    /**
     * Contact Label field in *FooterSlice → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer_slice.primary.contactLabel
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    contactLabel: prismicT.KeyTextField;
    /**
     * Contact Annotation field in *FooterSlice → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer_slice.primary.contactAnnotation
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    contactAnnotation: prismicT.RichTextField;
    /**
     * Email field in *FooterSlice → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer_slice.primary.email
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    email: prismicT.KeyTextField;
    /**
     * Phone field in *FooterSlice → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer_slice.primary.phone
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    phone: prismicT.KeyTextField;
    /**
     * Whats App field in *FooterSlice → Primary*
     *
     * - **Field Type**: Number
     * - **Placeholder**: *None*
     * - **API ID Path**: footer_slice.primary.whatsApp
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    whatsApp: prismicT.NumberField;
    /**
     * Social Label field in *FooterSlice → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer_slice.primary.socialLabel
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    socialLabel: prismicT.KeyTextField;
    /**
     * LinkedIn field in *FooterSlice → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: footer_slice.primary.linkedIn
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    linkedIn: prismicT.LinkField;
    /**
     * GitHub field in *FooterSlice → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: footer_slice.primary.gitHub
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    gitHub: prismicT.LinkField;
    /**
     * Twitter field in *FooterSlice → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: footer_slice.primary.twitter
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    twitter: prismicT.LinkField;
    /**
     * Company Label field in *FooterSlice → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer_slice.primary.companyLabel
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    companyLabel: prismicT.KeyTextField;
    /**
     * Kvk field in *FooterSlice → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer_slice.primary.kvk
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    kvk: prismicT.KeyTextField;
    /**
     * Btw field in *FooterSlice → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer_slice.primary.btw
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    btw: prismicT.KeyTextField;
    /**
     * Iban field in *FooterSlice → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer_slice.primary.iban
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    iban: prismicT.KeyTextField;
    /**
     * Location Label field in *FooterSlice → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer_slice.primary.locationLabel
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    locationLabel: prismicT.KeyTextField;
    /**
     * City field in *FooterSlice → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer_slice.primary.city
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    city: prismicT.KeyTextField;
    /**
     * Location field in *FooterSlice → Primary*
     *
     * - **Field Type**: GeoPoint
     * - **Placeholder**: *None*
     * - **API ID Path**: footer_slice.primary.location
     * - **Documentation**: https://prismic.io/docs/core-concepts/geopoint
     *
     */
    location: prismicT.GeoPointField;
}
/**
 * Default variation for FooterSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: `FooterSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FooterSliceSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<FooterSliceSliceDefaultPrimary>, never>;
/**
 * Slice variation for *FooterSlice*
 *
 */
type FooterSliceSliceVariation = FooterSliceSliceDefault;
/**
 * FooterSlice Shared Slice
 *
 * - **API ID**: `footer_slice`
 * - **Description**: `FooterSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FooterSliceSlice = prismicT.SharedSlice<"footer_slice", FooterSliceSliceVariation>;
/**
 * Primary content in HeroSlice → Primary
 *
 */
interface HeroSliceSliceDefaultPrimary {
    /**
     * Intro field in *HeroSlice → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: hero_slice.primary.intro
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    intro: prismicT.RichTextField;
    /**
     * Title field in *HeroSlice → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: hero_slice.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Sub Text field in *HeroSlice → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: hero_slice.primary.subText
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    subText: prismicT.RichTextField;
    /**
     * Reactify title field in *HeroSlice → Primary*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: hero_slice.primary.reactifyTitle
     * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
     *
     */
    reactifyTitle: prismicT.BooleanField;
}
/**
 * Default variation for HeroSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: `HeroSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSliceSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<HeroSliceSliceDefaultPrimary>, never>;
/**
 * Slice variation for *HeroSlice*
 *
 */
type HeroSliceSliceVariation = HeroSliceSliceDefault;
/**
 * HeroSlice Shared Slice
 *
 * - **API ID**: `hero_slice`
 * - **Description**: `HeroSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSliceSlice = prismicT.SharedSlice<"hero_slice", HeroSliceSliceVariation>;
/**
 * Default variation for PageContentSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: `PageContent`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type PageContentSliceDefault = prismicT.SharedSliceVariation<"default", Record<string, never>, never>;
/**
 * Slice variation for *PageContentSlice*
 *
 */
type PageContentSliceVariation = PageContentSliceDefault;
/**
 * PageContentSlice Shared Slice
 *
 * - **API ID**: `page_content`
 * - **Description**: `PageContent`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type PageContentSlice = prismicT.SharedSlice<"page_content", PageContentSliceVariation>;
/**
 * Primary content in ProjectsSlice → Primary
 *
 */
interface ProjectsSliceSliceDefaultPrimary {
    /**
     * Title field in *ProjectsSlice → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: projects_slice.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Explanation field in *ProjectsSlice → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: projects_slice.primary.explanation
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    explanation: prismicT.RichTextField;
}
/**
 * Default variation for ProjectsSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: `ProjectsSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProjectsSliceSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ProjectsSliceSliceDefaultPrimary>, never>;
/**
 * Slice variation for *ProjectsSlice*
 *
 */
type ProjectsSliceSliceVariation = ProjectsSliceSliceDefault;
/**
 * ProjectsSlice Shared Slice
 *
 * - **API ID**: `projects_slice`
 * - **Description**: `ProjectsSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProjectsSliceSlice = prismicT.SharedSlice<"projects_slice", ProjectsSliceSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { ArticleDocumentData, ArticleDocumentDataSlicesSlice, ArticleDocument, ConfigDocumentData, ConfigDocument, LayoutDocumentData, LayoutDocumentDataSlicesSlice, LayoutDocument, PageDocumentData, PageDocumentDataSlicesSlice, PageDocument, ProjectDocumentData, ProjectDocument, AllDocumentTypes, AngleSliceSliceDefault, AngleSliceSliceInverted, AngleSliceSliceVariation, AngleSliceSlice, ArticleCodeSnippetSliceSliceDefaultPrimary, ArticleCodeSnippetSliceSliceDefault, ArticleCodeSnippetSliceSliceVariation, ArticleCodeSnippetSliceSlice, ArticleContentSliceSliceDefaultPrimary, ArticleContentSliceSliceDefault, ArticleContentSliceSliceVariation, ArticleContentSliceSlice, ArticleSliceSliceDefaultPrimary, ArticleSliceSliceDefault, ArticleSliceSliceVariation, ArticleSliceSlice, ContentSliceSliceDefaultPrimary, ContentSliceSliceDefault, ContentSliceSliceImageLeftPrimary, ContentSliceSliceImageLeft, ContentSliceSliceImageLeftInvertedPrimary, ContentSliceSliceImageLeftInverted, ContentSliceSliceTwoColumnsTextPrimary, ContentSliceSliceTwoColumnsText, ContentSliceSliceTwoColumnsTextInvertedPrimary, ContentSliceSliceTwoColumnsTextInverted, ContentSliceSliceInvertedPrimary, ContentSliceSliceInverted, ContentSliceSliceVariation, ContentSliceSlice, FileDownloadSliceDefaultPrimary, FileDownloadSliceDefault, FileDownloadSliceVariation, FileDownloadSlice, FooterSliceSliceDefaultPrimary, FooterSliceSliceDefault, FooterSliceSliceVariation, FooterSliceSlice, HeroSliceSliceDefaultPrimary, HeroSliceSliceDefault, HeroSliceSliceVariation, HeroSliceSlice, PageContentSliceDefault, PageContentSliceVariation, PageContentSlice, ProjectsSliceSliceDefaultPrimary, ProjectsSliceSliceDefault, ProjectsSliceSliceVariation, ProjectsSliceSlice };
    }
}
