// This file is generated by Slice Machine. Update with care!

import AngleSlice from './AngleSlice';
import ArticleCodeSnippetSlice from './ArticleCodeSnippetSlice';
import ArticleContentSlice from './ArticleContentSlice';
import ArticleSlice from './ArticleSlice';
import ContentSlice from './ContentSlice';
import FooterSlice from './FooterSlice';
import HeroSlice from './HeroSlice';
import ProjectsSlice from './ProjectsSlice';

export {
	AngleSlice,
	ArticleCodeSnippetSlice,
	ArticleContentSlice,
	ArticleSlice,
	ContentSlice,
	FooterSlice,
	HeroSlice,
	ProjectsSlice,
};

export const components = {
	angle_slice: AngleSlice,
	article_code_snippet_slice: ArticleCodeSnippetSlice,
	article_content_slice: ArticleContentSlice,
	article_slice: ArticleSlice,
	content_slice: ContentSlice,
	footer_slice: FooterSlice,
	hero_slice: HeroSlice,
	projects_slice: ProjectsSlice,
};
