// This file is generated by Slice Machine. Update with care!

import ContentSlice from './ContentSlice';
import HeroSlice from './HeroSlice';
import ProjectsSlice from './ProjectsSlice';

export {
	ContentSlice,
	HeroSlice,
	ProjectsSlice,
};

export const components = {
	content_slice: ContentSlice,
	hero_slice: HeroSlice,
	projects_slice: ProjectsSlice,
};
