// This file is generated by Slice Machine. Update with care!

import AngleSlice from './AngleSlice';
import ContentSlice from './ContentSlice';
import FooterSlice from './FooterSlice';
import HeroSlice from './HeroSlice';
import ProjectsSlice from './ProjectsSlice';

export {
	AngleSlice,
	ContentSlice,
	FooterSlice,
	HeroSlice,
	ProjectsSlice,
};

export const components = {
	angle_slice: AngleSlice,
	content_slice: ContentSlice,
	footer_slice: FooterSlice,
	hero_slice: HeroSlice,
	projects_slice: ProjectsSlice,
};
